/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UASP;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC BAY
 */
public class TiketBioskop extends javax.swing.JInternalFrame {

    public Statement st;
    public ResultSet rs;
    Connection cn = UASP.koneksi.getKoneksi();
    /**
     * Creates new form TiketBioskop
     */
    public TiketBioskop() {
        initComponents();
    }

    public void cari(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Judul Film");
        tbl.addColumn("Jam Tayang");
        tbl.addColumn("No Kursi");
        tbl.addColumn("Jumlah Tiket");
        tbl.addColumn("Total Harga");
        
        try{
            String sql = "SELECT * FROM tiket_bioskop WHERE no_kursi like '%" + caritxt.getText() + "%' OR judul_film like '%" + caritxt.getText() + "%' OR jam_tayang like '%" + caritxt.getText() + "%' OR jumlah_tiket like '%" + caritxt.getText() + "%' OR total like '%" + caritxt.getText() + "%'";
            Connection cn = (Connection) koneksi.getKoneksi();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                tbl.addRow(new Object[]{
                rs.getString("judul_film"),
                rs.getString("jam_tayang"),
                rs.getString("no_kursi"),
                rs.getString("jumlah_tiket"),
                rs.getString("total")
                });
                tabel.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void clear(){
        jdlfilmtxt.setSelectedIndex(0);
        jamtayangtxt.setSelectedIndex(0);
        nokursitxt.setText("");
        jmltikettxt.setText("");
        totaltxt.setText("");
    }
    
    void clearcari(){
        caritxt.setText("");
    }
    
    public void tampilan(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Judul Film");
        tbl.addColumn("Jam Tayang");
        tbl.addColumn("No Kursi");
        tbl.addColumn("Jumlah Tiket");
        tbl.addColumn("Total Harga");
        
        try{
            Statement st = (Statement) koneksi.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tiket_bioskop");
            while(rs.next()){
                tbl.addRow(new Object[]{
                rs.getString("judul_film"),
                rs.getString("jam_tayang"),
                rs.getString("no_kursi"),
                rs.getString("jumlah_tiket"),
                rs.getString("total")
                });
                tabel.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdlfilmtxt = new javax.swing.JComboBox<>();
        jamtayangtxt = new javax.swing.JComboBox<>();
        nokursitxt = new javax.swing.JTextField();
        jmltikettxt = new javax.swing.JTextField();
        prosestxt = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        tampil = new javax.swing.JButton();
        cetakbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        simpanbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        caritxt = new javax.swing.JTextField();
        caribtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Pemesanan Tiket Bioskop");

        jLabel2.setText("Judul Film     :");

        jLabel3.setText("Jam Tayang  :");

        jLabel4.setText("Nomor Kursi :");

        jLabel5.setText("Jumlah Tiket  :");

        jdlfilmtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Judul Film", "Titanic", "The Flash", "Avenger" }));

        jamtayangtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jam Tayang", "09.00 am", "03.00 pm", "07.00 pm" }));

        nokursitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokursitxtActionPerformed(evt);
            }
        });

        prosestxt.setText("Proses");
        prosestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosestxtActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        tampil.setText("Tampil");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });

        cetakbtn.setText("Cetak");
        cetakbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Harga   : Rp");

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        simpanbtn.setText("Simpan");
        simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbtnActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul Film", "Jam Tayang", "No kursi", "Jumlah Tiket", "Total"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        caribtn.setText("Cari");
        caribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbatal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jamtayangtxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmltikettxt)
                            .addComponent(nokursitxt)
                            .addComponent(totaltxt)
                            .addComponent(jdlfilmtxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prosestxt)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cetakbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caritxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jdlfilmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jamtayangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nokursitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jmltikettxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cetakbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prosestxt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal)
                    .addComponent(simpanbtn))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caritxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caribtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nokursitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokursitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nokursitxtActionPerformed

    private void cetakbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakbtnActionPerformed
        try{
            String path = "src/UASP/Report.jasper";
            Connection cn = UASP.koneksi.getKoneksi();
            
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(path, parameters, cn);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error Displaying Report :" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cetakbtnActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        try{
            String sql = "SELECT * FROM tiket_bioskop";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.execute();
            tampilan();
            clear();
          
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan" + e);
        }
    }//GEN-LAST:event_tampilActionPerformed

    private void prosestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosestxtActionPerformed
        int jmltkt = Integer.parseInt(jmltikettxt.getText());
        int total = jmltkt*40000;
        totaltxt.setText(Integer.toString(total));
    }//GEN-LAST:event_prosestxtActionPerformed

    private void simpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbtnActionPerformed
        try{
            String sql = "INSERT INTO tiket_bioskop VALUES ('" + jdlfilmtxt.getSelectedItem() + "', '" + jamtayangtxt.getSelectedItem() + "', '" + nokursitxt.getText() + "', '" + jmltikettxt.getText() + "', '" + totaltxt.getText() + "')";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampilan();
            clear();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }//GEN-LAST:event_simpanbtnActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        clear();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void caribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribtnActionPerformed
        cari();
        clearcari();
    }//GEN-LAST:event_caribtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        try{
            String sql = "UPDATE tiket_bioskop SET judul_film='" + jdlfilmtxt.getSelectedItem() + "', jam_tayang = '" + jamtayangtxt.getSelectedItem() + "', no_kursi = '" + nokursitxt.getText() + "', jumlah_tiket = '" + jmltikettxt.getText() + "', total = '" + totaltxt.getText() + "' WHERE no_kursi ='" + nokursitxt.getText() + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
            tampilan();
            clear();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diedit" + e);
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        try{
            String sql = "DELETE FROM tiket_bioskop WHERE no_kursi = '" + nokursitxt.getText() + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            tampilan();
            clear();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e);
        }
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris = tabel.rowAtPoint(evt.getPoint());
        String jdlfilm = tabel.getValueAt(baris, 0).toString();
        jdlfilmtxt.setSelectedItem(jdlfilm);
        String jamtayang = tabel.getValueAt(baris, 1).toString();
        jamtayangtxt.setSelectedItem(jamtayang);
        String nokursi = tabel.getValueAt(baris, 2).toString();
        nokursitxt.setText(nokursi);
        String jmltiket = tabel.getValueAt(baris, 3).toString();
        jmltikettxt.setText(jmltiket);
        String total = tabel.getValueAt(baris, 4).toString();
        totaltxt.setText(total);
    }//GEN-LAST:event_tabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton caribtn;
    private javax.swing.JTextField caritxt;
    private javax.swing.JButton cetakbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jamtayangtxt;
    private javax.swing.JComboBox<String> jdlfilmtxt;
    private javax.swing.JTextField jmltikettxt;
    private javax.swing.JTextField nokursitxt;
    private javax.swing.JButton prosestxt;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tampil;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
